/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontend;

import Backend.Models.Instructor;
import Backend.Models.User;
import javax.swing.JFrame;

/**
 *
 * @author Pc
 */
public class InstructorDashboard extends javax.swing.JPanel {


    private Instructor instructor; // store the logged-in instructor

    public InstructorDashboard(Instructor instructor) {
        this.instructor = instructor; // store user info
        initComponents();

        jLabel1.setText("Instructor Dashboard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageCourses = new javax.swing.JButton();
        btnManageLessons = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Instructor Dashboard");

        btnManageCourses.setBackground(new java.awt.Color(0, 0, 255));
        btnManageCourses.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManageCourses.setForeground(new java.awt.Color(255, 255, 255));
        btnManageCourses.setText("Manage Courses");
        btnManageCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCoursesActionPerformed(evt);
            }
        });

        btnManageLessons.setBackground(new java.awt.Color(255, 0, 0));
        btnManageLessons.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManageLessons.setForeground(new java.awt.Color(255, 255, 255));
        btnManageLessons.setText("Manage Lessons");
        btnManageLessons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageLessonsActionPerformed(evt);
            }
        });

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jButton1.setText("Create Quiz");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnManageCourses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageLessons, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnManageCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnManageLessons, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCoursesActionPerformed
    JFrame parentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
    parentFrame.dispose();

    JFrame dash = new JFrame("Manage Courses");
    dash.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    dash.getContentPane().add(new ManageCourse(instructor));
    dash.pack();
    dash.setLocationRelativeTo(null);
    dash.setVisible(true);
    }//GEN-LAST:event_btnManageCoursesActionPerformed

    private void btnManageLessonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageLessonsActionPerformed
    JFrame parentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
    parentFrame.dispose();

    JFrame dash = new JFrame("Manage Lessons");
    dash.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    dash.getContentPane().add(new ManageLessons(instructor));
    dash.pack();
    dash.setLocationRelativeTo(null);
    dash.setVisible(true);
    }//GEN-LAST:event_btnManageLessonsActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
    JFrame currentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
    currentFrame.dispose();
    
    JFrame homeFrame = new JFrame("Skill-Forge");
    homeFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    homeFrame.getContentPane().add(new Home());
    homeFrame.pack();
    homeFrame.setLocationRelativeTo(null);
    homeFrame.setVisible(true);    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCourses;
    private javax.swing.JButton btnManageLessons;
    private javax.swing.JButton btnback;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
