/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontend;

import Backend.Models.Course;
import Backend.Models.Instructor;
import Backend.Models.Lesson;
import Backend.Services.InstructorService;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pc
 */
public class ManageLessons extends javax.swing.JPanel {
    private Instructor instructor;
    private InstructorService instructorService;
    private Course selectedCourse;
    private Lesson selectedLesson;
    private javax.swing.event.ListSelectionListener coursesListener;
    private javax.swing.event.ListSelectionListener lessonsListener;
    
public ManageLessons(Instructor instructor) {
    this.instructor = instructor;
    this.instructorService = new InstructorService(instructor);

    initComponents();
    loadCourses();
    addListeners();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfLessonId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfTitle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfContent = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lessonsTable = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        coursesTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfuLessonId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfuTitle = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfuContent = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tfResources = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfuResources = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Lessons");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fill the form that needed to add a lesson");

        jLabel3.setText("LessonId");

        jLabel4.setText("Title");

        jLabel5.setText("Content");

        tfContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContentActionPerformed(evt);
            }
        });

        lessonsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "lessonId", "title", "content", "resources"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        lessonsTable.setColumnSelectionAllowed(true);
        lessonsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lessonsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lessonsTable);
        lessonsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        coursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "courseId", "title", "description", "instructorId"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        coursesTable.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(coursesTable);
        coursesTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Select the row that needed to be updated");

        jLabel7.setText("LessonId");

        tfuLessonId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfuLessonIdActionPerformed(evt);
            }
        });

        jLabel8.setText("Title");

        tfuTitle.setText("\n");
        tfuTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfuTitleActionPerformed(evt);
            }
        });

        jLabel9.setText("Content");

        tfuContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfuContentActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel10.setText("Resources");

        tfResources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfResourcesActionPerformed(evt);
            }
        });

        jLabel11.setText("Resources");

        tfuResources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfuResourcesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfContent)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                                .addGap(6, 6, 6))
                                            .addComponent(tfLessonId, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfResources)))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btnAdd)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfuLessonId, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfuContent)
                                            .addComponent(tfuResources, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(btnUpdate))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(528, 528, 528)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfLessonId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfResources, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(btnAdd))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfuLessonId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tfuContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tfuResources, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(btnUpdate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfuLessonIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfuLessonIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfuLessonIdActionPerformed

    private void tfuTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfuTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfuTitleActionPerformed

    private void tfuContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfuContentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfuContentActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
   if (selectedLesson == null || selectedCourse == null) {
        JOptionPane.showMessageDialog(this, "Please select a lesson to update!");
        return;
    }
    
    try {
        int oldLessonId = selectedLesson.getLessonId();
        int newLessonId = Integer.parseInt(tfuLessonId.getText().trim());
        String title = tfuTitle.getText().trim();
        String content = tfuContent.getText().trim();
        String resourcesText = tfuResources.getText().trim();
        
        if(title.isEmpty() || content.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill title and content!");
            return;
        }
        
        ArrayList<String> resources = new ArrayList<>();
        if(!resourcesText.isEmpty()) {
            String[] resourceArray = resourcesText.split(",");
            for (int i = 0; i < resourceArray.length; i++) {
                resources.add(resourceArray[i].trim());
            }
        }
        
        boolean updated = instructorService.updateLesson(selectedCourse.getCourseId(), oldLessonId, newLessonId, title, content, resources);
        
        if (updated) {
            JOptionPane.showMessageDialog(this, "Lesson updated successfully!");
            loadLessons(selectedCourse);
            clearUpdateForm();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update lesson!");
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter valid lesson ID!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error updating lesson!");
    }
      }//GEN-LAST:event_btnUpdateActionPerformed

    private void tfuResourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfuResourcesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfuResourcesActionPerformed

    private void tfResourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfResourcesActionPerformed
       
    }//GEN-LAST:event_tfResourcesActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    if (selectedCourse == null) {
        JOptionPane.showMessageDialog(this, "Select a course first!");
        return;
    }
    try {
        int id = Integer.parseInt(tfLessonId.getText().trim());
        String title = tfTitle.getText().trim();
        String content = tfContent.getText().trim();
        String resourcesText = tfResources.getText().trim();
        
        if(title.isEmpty() || content.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill title and content!");
            return;
        }
        
        ArrayList<String> resources = new ArrayList<>();
        if(!resourcesText.isEmpty()) {
            String[] resourceArray = resourcesText.split(",");
            for (int i = 0; i < resourceArray.length; i++) {
                resources.add(resourceArray[i].trim());
            }
        }

        boolean added = instructorService.addLesson(selectedCourse, id, title, content, resources);
        if (added) {
            JOptionPane.showMessageDialog(this, "Lesson added successfully!");
            loadLessons(selectedCourse);
            clearAddForm();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add lesson! Lesson ID might already exist.");
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Please enter valid lesson ID!");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Invalid input!");
    }

     }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
     if (selectedLesson == null || selectedCourse == null) {
        JOptionPane.showMessageDialog(this, "Please select a lesson to delete!");
        return;
    }
    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure?", "Delete Lesson", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        boolean deleted = instructorService.deleteLesson(selectedCourse, selectedLesson.getLessonId());
        if (deleted) {
            JOptionPane.showMessageDialog(this, "Lesson deleted successfully!");
            loadLessons(selectedCourse);
            clearUpdateForm();
            selectedLesson = null;
        } else {
            JOptionPane.showMessageDialog(this, "Failed to delete lesson!");
        }                                 
        }    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tfContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContentActionPerformed

    private void lessonsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lessonsTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lessonsTableMouseClicked

private void addListeners() {
    coursesListener = new javax.swing.event.ListSelectionListener() {
        public void valueChanged(javax.swing.event.ListSelectionEvent e) {
            if (!e.getValueIsAdjusting()) {
                int row = coursesTable.getSelectedRow();
                if (row >= 0) {
                    int courseId = (int) coursesTable.getValueAt(row, 0);
                    selectedCourse = instructorService.getCourseById(courseId);
                    loadLessons(selectedCourse);
                }
            }
        }
    };
    coursesTable.getSelectionModel().addListSelectionListener(coursesListener);

    lessonsListener = new javax.swing.event.ListSelectionListener() {
        public void valueChanged(javax.swing.event.ListSelectionEvent e) {
            if (!e.getValueIsAdjusting()) {
                int row = lessonsTable.getSelectedRow();
                if (row >= 0 && selectedCourse != null) {
                    int lessonId = (int) lessonsTable.getValueAt(row, 0);
                    selectedLesson = selectedCourse.getLessonById(lessonId);
                    if (selectedLesson != null) {
                        tfuLessonId.setText(String.valueOf(selectedLesson.getLessonId()));
                        tfuTitle.setText(selectedLesson.getTitle());
                        tfuContent.setText(selectedLesson.getContent());
                        tfuResources.setText(String.join(",", selectedLesson.getResources()));
                    }
                }
            }
        }
    };
    lessonsTable.getSelectionModel().addListSelectionListener(lessonsListener);
}

private void loadCourses() {
    DefaultTableModel model = (DefaultTableModel) coursesTable.getModel();
    model.setRowCount(0);
    ArrayList<Integer> courseIds = instructorService.getCreatedCoursesIds();
    if (courseIds != null) {
        for (int i = 0; i < courseIds.size(); i++) {
            Course c = instructorService.getCourseById(courseIds.get(i));
            if (c != null) {
                model.addRow(new Object[]{c.getCourseId(), c.getTitle(), c.getDescription(), c.getInstructorId()});
            }
        }
    }
}

private void loadLessons(Course course) {
    if (course == null) return;
    DefaultTableModel model = (DefaultTableModel) lessonsTable.getModel();
    model.setRowCount(0);
    ArrayList<Lesson> lessons = instructorService.getLessons(course);
    if (lessons != null) {
        for (int i = 0; i < lessons.size(); i++) {
            Lesson l = lessons.get(i);
            model.addRow(new Object[]{l.getLessonId(), l.getTitle(), l.getContent(), String.join(",", l.getResources())});
        }
    }
}

private void clearAddForm() {
    tfLessonId.setText("");
    tfTitle.setText("");
    tfContent.setText("");
    tfResources.setText("");
}

private void clearUpdateForm() {
    tfuLessonId.setText("");
    tfuTitle.setText("");
    tfuContent.setText("");
    tfuResources.setText("");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTable coursesTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable lessonsTable;
    private javax.swing.JTextField tfContent;
    private javax.swing.JTextField tfLessonId;
    private javax.swing.JTextField tfResources;
    private javax.swing.JTextField tfTitle;
    private javax.swing.JTextField tfuContent;
    private javax.swing.JTextField tfuLessonId;
    private javax.swing.JTextField tfuResources;
    private javax.swing.JTextField tfuTitle;
    // End of variables declaration//GEN-END:variables
}
