/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontend;

import Backend.Models.Instructor;
import Backend.Models.Student;
import Backend.Models.User;
import Backend.Services.AuthService;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author pola-nasser13
 */
public class SignIn extends javax.swing.JPanel {

    /**
     * Creates new form SignIn
     */

    private String role;

    public SignIn(String role) {
        this.role = role;
        initComponents();
        this.setSize(800, 800);       
this.setPreferredSize(new java.awt.Dimension(600, 500));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SignIn = new javax.swing.JButton();
        Password = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setText("Email:");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel2.setText("Pass.:");

        SignIn.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        SignIn.setText("Sign in");
        SignIn.addActionListener(this::SignInActionPerformed);

        Password.addActionListener(this::PasswordActionPerformed);

        Email.addActionListener(this::EmailActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInActionPerformed
try {
    String email = Email.getText() != null ? Email.getText().trim() : "";
    String password = Password.getText() != null ? Password.getText() : "";

  
    if (email.isEmpty()) throw new Exception("Email cannot be empty");
    int atPos = email.indexOf("@");
    int dotPos = email.lastIndexOf(".");
    if (atPos <= 0 || dotPos <= atPos + 1 || dotPos == email.length() - 1) {
        throw new Exception("Invalid email format");
    }

    if (password.length() < 4) throw new Exception("Password too short (min 4 characters)");


    if (role == null || role.isEmpty()) throw new Exception("Role not selected");

    AuthService auth = new AuthService();


    if (role.equalsIgnoreCase("Instructor")) {
        Instructor instructor = auth.loginInstructor(email, password);
        if (instructor == null) {
            JOptionPane.showMessageDialog(this, "Invalid email or password!");
            return;
        }

        JOptionPane.showMessageDialog(this, "Instructor logged in successfully!");
        Email.setText("");
        Password.setText("");


        JFrame parentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentFrame != null) parentFrame.dispose();
        JFrame dash = new JFrame("Instructor Dashboard");
        dash.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dash.getContentPane().add(new InstructorDashboard(instructor));
        dash.pack();
        dash.setLocationRelativeTo(null);
        dash.setVisible(true);
        return;
    }

    
    if (role.equalsIgnoreCase("Student")) {
        Student student = auth.loginStudent(email, password);
        if (student == null) {
            JOptionPane.showMessageDialog(this, "Invalid email or password!");
            return;
        }

        JOptionPane.showMessageDialog(this, "Student logged in successfully!");
        Email.setText("");
        Password.setText("");

        JFrame parentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentFrame != null) parentFrame.dispose();

   
        JFrame dash = new JFrame("Student Dashboard");
        dash.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dash.getContentPane().add(new StudentDashboard(student));
        dash.pack();
        dash.setLocationRelativeTo(null);
        dash.setVisible(true);
        return;
    }

    JOptionPane.showMessageDialog(this, "Invalid role selected!");

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    e.printStackTrace();
}



    }//GEN-LAST:event_SignInActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Password;
    private javax.swing.JButton SignIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
