/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontend;

import Backend.Models.Certificate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Backend.Models.Course;
import Backend.Models.Lesson;
import Backend.Models.Student;
import Backend.Services.CourseService;
import Backend.Services.StudentService;
import java.util.ArrayList;
import javax.swing.JFrame;



/**
 *
 * @author Mohamed Walaa
 */
public class StudentDashboard extends javax.swing.JPanel {
    
    StudentService studentService;
    private DefaultTableModel availableModel;
    private DefaultTableModel enrolledModel;
    private DefaultTableModel lessonsModel;
    private int selectedCourseId = -1; 
    private String selectedCourseName = ""; 
    
    public StudentDashboard(Student student) {
        studentService = new StudentService(student);
        initComponents();
        
        availableModel = (DefaultTableModel) availableCourseTable.getModel();
        enrolledModel = (DefaultTableModel) enrolledCoursesTable.getModel();
        lessonsModel = (DefaultTableModel) lessonTable.getModel();
        
        loadAvailableCourses();
        loadEnrolledCourses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        availableCourseTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        enrolledCoursesTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        enroll = new javax.swing.JButton();
        accesslessons = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lessonTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        getQuizButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        certificatesTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        viewAndDownloadCertButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setName(""); // NOI18N

        jScrollPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane1.setToolTipText("");

        availableCourseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Instructor", "Number of Lessons"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(availableCourseTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enrolled Courses");

        jScrollPane2.setBorder(null);
        jScrollPane2.setViewportBorder(new javax.swing.border.MatteBorder(null));

        enrolledCoursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Instructor", "Number of Lessons", "Progress"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(enrolledCoursesTable);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Available Courses");

        enroll.setText("ENROLL");
        enroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollActionPerformed(evt);
            }
        });

        accesslessons.setText("ACCESS LESSONS");
        accesslessons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accesslessonsActionPerformed(evt);
            }
        });

        lessonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Lesson ID", "Lesson Name", "Content", "Completed?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(lessonTable);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Certificates");

        btnback.setBackground(new java.awt.Color(255, 0, 0));
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        getQuizButton.setText("Get Quiz");
        getQuizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getQuizButtonActionPerformed(evt);
            }
        });

        certificatesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Certificate ID", "Course ID", "Issue Date"
            }
        ));
        jScrollPane4.setViewportView(certificatesTable);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Lessons");

        viewAndDownloadCertButton.setText("View and Download");
        viewAndDownloadCertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAndDownloadCertButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Select lesson first:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(enroll)
                .addGap(326, 326, 326)
                .addComponent(accesslessons)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 821, Short.MAX_VALUE)
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(getQuizButton)
                                .addGap(45, 45, 45))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 91, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(96, 96, 96))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(viewAndDownloadCertButton)
                                .addGap(122, 122, 122))))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(1026, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(444, 444, 444)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane3)
                                    .addComponent(jScrollPane4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(viewAndDownloadCertButton)
                                    .addComponent(getQuizButton)
                                    .addComponent(jLabel5)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enroll)
                            .addComponent(accesslessons))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnback)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel4)
                    .addContainerGap(505, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadAvailableCourses() {
        availableModel.setRowCount(0);
        ArrayList<Course> approvedCourses = studentService.gerApprovedCourses();
        if (approvedCourses != null) {
            for (int i = 0; i < approvedCourses.size(); i++) {
                Course course = approvedCourses.get(i);
                CourseService courseService = new CourseService(course);
                availableModel.addRow(new Object[]{
                    course.getCourseId(),
                    course.getTitle(),
                    courseService.getInstructorName(),
                    course.getLessons().size()
                });
            }
        }
    }

    private void loadEnrolledCourses() {
        enrolledModel.setRowCount(0);
        ArrayList<Course> enrolledCourses = studentService.getEnrolledCourses();
        if (enrolledCourses != null) {
            for (int i = 0; i < enrolledCourses.size(); i++) {
                Course course = enrolledCourses.get(i);
                CourseService courseService = new CourseService(course);
                int completed = studentService.getCompletedLessonsCount(course.getCourseId());
                int total = course.getLessons().size();
                enrolledModel.addRow(new Object[]{
                    course.getCourseId(),
                    course.getTitle(),
                    courseService.getInstructorName(),
                    total,
                    completed + "/" + total
                });
            }
        }
    }

    private void loadLessonsForCourse(int courseId) {
        lessonsModel.setRowCount(0);
        Course course = studentService.getCourse(courseId);
        if (course != null) {
            ArrayList<Lesson> lessons = course.getLessons();
            for (int i = 0; i < lessons.size(); i++) {
                Lesson lesson = lessons.get(i);
                boolean completed = studentService.isLessonCompleted(courseId, lesson.getLessonId());
                lessonsModel.addRow(new Object[]{
                    lesson.getLessonId(),
                    lesson.getTitle(),
                    lesson.getContent(),
                    completed ? "Yes" : "No"
                });
            }
        }
    }
    
    private void accesslessonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accesslessonsActionPerformed
    int selectedRow = enrolledCoursesTable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a course first.");
        return;
    }

    selectedCourseId = (Integer) enrolledModel.getValueAt(selectedRow, 0);
    selectedCourseName = (String) enrolledModel.getValueAt(selectedRow, 1);
    loadLessonsForCourse(selectedCourseId);
    
    jLabel3.setText("Lessons - " + selectedCourseName);                         
    }//GEN-LAST:event_accesslessonsActionPerformed

    private void enrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollActionPerformed
         int selectedRow = availableCourseTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to enroll.");
            return;
        }

        int courseId = (Integer) availableModel.getValueAt(selectedRow, 0);
        
        boolean enrolled = studentService.enrollInCourse(courseId);
        if (enrolled) {
            JOptionPane.showMessageDialog(this, "Enrolled in course successfully!");
            loadEnrolledCourses();
            loadAvailableCourses();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to enroll! You might already be enrolled in this course.");
        }
    }//GEN-LAST:event_enrollActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
    JFrame currentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
    currentFrame.dispose();
    
    JFrame homeFrame = new JFrame("Skill-Forge");
    homeFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    homeFrame.getContentPane().add(new Home());
    homeFrame.pack();
    homeFrame.setLocationRelativeTo(null);
    homeFrame.setVisible(true);    }//GEN-LAST:event_btnbackActionPerformed

    private void getQuizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getQuizButtonActionPerformed
    int selectedRow = enrolledCoursesTable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a course first.");
        return;
    }

    int courseId = (Integer) enrolledModel.getValueAt(selectedRow, 0);
    
    int selectedLessonRow = lessonTable.getSelectedRow();
    if (selectedLessonRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a lesson first.");
        return;
    }

    int lessonId = (Integer) lessonsModel.getValueAt(selectedLessonRow, 0);

    JFrame currentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
    currentFrame.getContentPane().removeAll();
    currentFrame.getContentPane().add(new QuizPanel(studentService.getStudent(), courseId, lessonId, this));
    currentFrame.revalidate();
    currentFrame.repaint();
    }//GEN-LAST:event_getQuizButtonActionPerformed

    private void viewAndDownloadCertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAndDownloadCertButtonActionPerformed
        
    int selectedRow = certificatesTable.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a certificate first.");
        return;
    }

    String certId = (String) certificatesTable.getValueAt(selectedRow, 0);
    Certificate cert = studentService.getCertificateById(certId);

    JFrame currentFrame = (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
    currentFrame.getContentPane().removeAll();
    currentFrame.getContentPane().add(new CertificateView(cert));
    currentFrame.revalidate();
    currentFrame.repaint();
    }//GEN-LAST:event_viewAndDownloadCertButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accesslessons;
    private javax.swing.JTable availableCourseTable;
    private javax.swing.JButton btnback;
    private javax.swing.JTable certificatesTable;
    private javax.swing.JButton enroll;
    private javax.swing.JTable enrolledCoursesTable;
    private javax.swing.JButton getQuizButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable lessonTable;
    private javax.swing.JButton viewAndDownloadCertButton;
    // End of variables declaration//GEN-END:variables
}
