/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontend;

import Backend.Models.Question;
import java.util.ArrayList;

/**
 *
 * @author pola-nasser13
 */
public class SumbitQuiz extends javax.swing.JPanel {

    /**
     * Creates new form SumbitQuiz
     */
    private double score;
    private boolean passed;
    private int attempts;
    private ArrayList<Question> questions;
    private ArrayList<Integer> userAnswers;

    public SumbitQuiz(double score, boolean passed, int attempts, 
                     ArrayList<Question> questions, ArrayList<Integer> userAnswers) {
        initComponents();
        this.score = score;
        this.passed = passed;
        this.attempts = attempts;
        this.questions = questions;
        this.userAnswers = userAnswers;
        displayResults();
        makeFieldsReadOnly();
    }

    private void displayResults() {
        // Set basic results
        tfScore.setText(String.format("%.2f%%", score));
        tfNumOfAttempts.setText(String.valueOf(attempts));
        
        if (passed) {
            tfPassOrFail.setText("PASSED");
            tfPassOrFail.setForeground(new java.awt.Color(0, 128, 0)); // Green
            displayQuestionsAndAnswers();
        } else {
            tfPassOrFail.setText("FAILED");
            tfPassOrFail.setForeground(new java.awt.Color(255, 0, 0)); // Red
            QuestionsAndAnswers.setText("You must pass the quiz to see the correct answers and access the next lesson.\n\nYou can retake the quiz to improve your score.");
        }
    }

    private void displayQuestionsAndAnswers() {
        StringBuilder sb = new StringBuilder();
        sb.append("QUESTIONS AND CORRECT ANSWERS:\n\n");
        
        for (int i = 0; i < questions.size(); i++) {
            Question question = questions.get(i);
            sb.append("Question ").append(i + 1).append(": ").append(question.getText()).append("\n");
            
            ArrayList<String> choices = question.getChoices();
            int correctChoice = question.getCorrectChoice();
            int userAnswer = userAnswers.get(i);
            
            // Display all choices
            for (int j = 0; j < choices.size(); j++) {
                String choiceLabel = String.valueOf((char)('A' + j));
                String choiceText = choices.get(j);
                
                if (j == correctChoice) {
                    sb.append("✓ ").append(choiceLabel).append(") ").append(choiceText).append(" (CORRECT)\n");
                } else if (j == userAnswer) {
                    sb.append("✗ ").append(choiceLabel).append(") ").append(choiceText).append(" (YOUR ANSWER)\n");
                } else {
                    sb.append("  ").append(choiceLabel).append(") ").append(choiceText).append("\n");
                }
            }
            
            // Add spacing between questions
            sb.append("\n");
        }
        
        QuestionsAndAnswers.setText(sb.toString());
    }

    private void makeFieldsReadOnly() {
        tfScore.setEditable(false);
        tfPassOrFail.setEditable(false);
        tfNumOfAttempts.setEditable(false);
        QuestionsAndAnswers.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfScore = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNumOfAttempts = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfPassOrFail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        QuestionsAndAnswers = new java.awt.TextArea();

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        jLabel1.setText("QUIZ Result ");

        tfScore.addActionListener(this::tfScoreActionPerformed);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("Your score:");

        tfNumOfAttempts.addActionListener(this::tfNumOfAttemptsActionPerformed);

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel6.setText("Number of attempts:");

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel8.setText("Passed or failed");

        tfPassOrFail.addActionListener(this::tfPassOrFailActionPerformed);

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("If you fail, you will not be able to see the correct answers or access the next lesson. You must try again");

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel9.setText("Questions and Answers:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNumOfAttempts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(310, 310, 310))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(277, 277, 277))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPassOrFail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 6, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuestionsAndAnswers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfNumOfAttempts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tfPassOrFail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuestionsAndAnswers, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfScoreActionPerformed

    private void tfPassOrFailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPassOrFailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPassOrFailActionPerformed

    private void tfNumOfAttemptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumOfAttemptsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumOfAttemptsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea QuestionsAndAnswers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfNumOfAttempts;
    private javax.swing.JTextField tfPassOrFail;
    private javax.swing.JTextField tfScore;
    // End of variables declaration//GEN-END:variables
}
